---
title: "eda"
output: html_document
date: "2023-12-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(umap)
```

```{r}
data = read.csv("./data/contrywise_economicdata.csv")
head(data)
```

```{r}
model1 = lm(New.cases/Population~Import+Export+GDPperCapita+Inflation,data=data)
model2 = lm(Deathsper100Cases~Import+Export+GDPperCapita+Inflation,data=data)
model3 = lm(Recoveredper100Cases~Import+Export+GDPperCapita+Inflation,data=data)
result_model = rbind(summary(model1)$coefficients[,4],
                     summary(model2)$coefficients[,4],
                     summary(model3)$coefficients[,4])
row.names(result_model) = c("New Cases","Deaths Per 100 Cases","Recovered per 100 Cases")
result_model
```

```{r}
umapResult = umap(scale(data[c("GDPchange","GDPperCapita","Import","Export","Population")]))
umapdata = cbind(data[c("Country","WHO.Region")],data.frame(umapResult$layout))
colnames(umapdata) = c("Country","WHO.Region","umap1","umap2")
km = kmeans(scale(data[c("GDPchange","GDPperCapita","Import","Export","Population")]),6)
umapdata = cbind(umapdata,"cluster"= km$cluster)

```

```{r}
png("./fig/clusterandumap.png", width=1000, height=600)

p1 = umapdata %>%
  ggplot(aes(x=umap1,y=umap2,color=WHO.Region)) +
  geom_point() +
  theme(legend.position = "bottom")
p2 = umapdata %>%
  ggplot(aes(x=umap1,y=umap2,color=factor(cluster))) +
  geom_point() +
  theme(legend.position = "bottom")

gridExtra::grid.arrange(p1,p2,nrow=1)

dev.off()
```
